#!/bin/bash

echo "🚀 PixelPrompter Setup Guide"
echo "==========================="
echo ""
echo "To run this project, you need a Google Gemini API key."
echo ""
echo "📝 Steps to get your API key:"
echo "1. Go to https://ai.google.dev/"
echo "2. Click 'Get API Key' or 'Get started for free'"
echo "3. Sign in with your Google account"
echo "4. Create a new API key"
echo "5. Copy the API key"
echo ""
echo "🔧 Setup Instructions:"
echo "1. Create a .env file in this directory:"
echo "   touch .env"
echo ""
echo "2. Add your API key to the .env file:"
echo "   echo 'GEMINI_API_KEY=your_actual_api_key_here' > .env"
echo ""
echo "3. Run the application:"
echo "   ./.venv/bin/python app.py"
echo ""
echo "🌐 The application will be available at:"
echo "   http://localhost:5000"
echo ""
echo "📁 You can also upload PDFs and ask questions about them!"